server:
  port: 8080

spring:
  application:
    name: banking
  datasource:
    url: jdbc:h2:mem:banking;DB_CLOSE_ON_EXIT=TRUE;DATABASE_TO_UPPER=false
#    url: jdbc:postgresql://localhost:8021/postgres
#    username: postgres
#    password: postgres
    h2:
      console:
        enabled: true
        path: /h2-console
        settings:
          web-allow-others: true
    jpa:
      hibernate:
        ddl-auto: none
      properties.hibernate:
        temp.use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
      flyway:
        enabled: true


logging:
  level:
    org.springframework: INFO
    lt.denislav.banking: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security: INFO